#' Calculate the likelihood of a set of data in a GMM
#' @param ps Proportion of the data which was drawn from each cluster.
#' @param thetas matrix of theta parameters for each cluster
#' @param ranks a list of objects of class 'ranking', as generated by RMallow,
#' one for each cluster.
#' @return The log-likelihood of the parameters, given the data.
# L(\theta, \pi) = \sum_{i = 1}^N log[\sum_{g = 1}^G p_g*C(\theta_g)exp(-D_{\theta_g}(y_i\circ \pi_g))]
likelihoodGMM <- function(ps, thetas, ranks) {
  pvals <- log(rowSums(t(ps*t(pRank(ranks, thetas)))))
  return(sum(pvals))
}
